NELCCG.NHSUKFrontend.MvcApp/Models/ErrorViewModel.cs
using System;

namespace NELCCG.NHSUKFrontend.MvcApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public Exception Error { get; set; }
    }
}

NELCCG.NHSUKFrontend.MvcApp/Models/HeroExample.cs
using System.ComponentModel.DataAnnotations;

namespace NELCCG.NHSUKFrontend.MvcApp.Models
{
    public class HeroExample
    {
        [Display(Name = "Heading")]
        public string HeroTitle { get; set; }
        
        [Display(Name = "Text")]
        public string HeroMessage { get; set; }

        [Display(Name = "Image Url")]
        public string HeroImage { get; set; }
    }
}

NELCCG.NHSUKFrontend.MvcApp/Models/User.cs
namespace NELCCG.NHSUKFrontend.MvcApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class User
    {
        [Display(Name = "Given name")]
        public string GivenName { get; set; }

        public string Surname { get; set; }

        [Display(Name = "Date of birth")]
        public DateTime? DateOfBirth { get; set; }

        [Display(Name = "Favourite Colour")]
        public string FavouriteColour { get; set; }

        [Display(Name = "Favourite Colour (Other)")]
        public string FavouriteColourOther { get; set; }

        public List<string> Nationality { get; set; } = new List<string>();

        public List<string> ContactPreferences { get; set; } = new List<string>();

        public string ContactPreferenceEmail { get; set; }

        public string ContactPreferenceTelephone { get; set; }

        public string ContactPreferenceTextMessage { get; set; }

        public string Biography { get; set; }

        public string Role { get; set; }

    }
}

NELCCG.NHSUKFrontend.MvcApp/Controllers/ContentController.cs
namespace NELCCG.NHSUKFrontend.MvcApp.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using NELCCG.NHSUKFrontend.MvcApp.Models;

    public class ContentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CareCard()
        {
            return View();
        }

        public IActionResult Details()
        {
            return View();
        }

        public IActionResult DoDontLists()
        {
            return View();
        }

        public IActionResult Hero(HeroExample model)
        {
            if (this.Request.Method == "GET")
            {
                model.HeroTitle = "Hero";
            }
            
            return View(model);
        }

        public IActionResult Image()
        {
            return View();
        }

        public IActionResult InsetText()
        {
            return View();
        }

        public IActionResult SummaryList()
        {
            return View();
        }

        public IActionResult Table()
        {
            return View();
        }

        public IActionResult Tag()
        {
            return View();
        }

        public IActionResult WarningCallout()
        {
            return View();
        }

    }
}

NELCCG.NHSUKFrontend.MvcApp/Controllers/FormController.cs
namespace NELCCG.NHSUKFrontend.MvcApp.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using NELCCG.NHSUKFrontend.MvcApp.Models;
    using NELCCG.NHSUKFrontend.Razor.Helpers;
    using System;
    using System.Collections.Generic;

    public class FormController : Controller
    {

        public IActionResult Index(User model)
        {
            if (this.Request.Method == "GET")
            {
                model.Biography = "This is line 1\nThis is line 2\t\tThis is tabbed";
                model.FavouriteColour = "Other";
                model.FavouriteColourOther = "Purple";
                model.Nationality = new List<string> { "british", "other" };
                // add invalid date of birth to force an error (shown in view)
                model.DateOfBirth = DateTime.Now.AddDays(5);
            }

            if (this.Request.Method == "POST")
            {
                DateInputHelper.UpdateFromFormRequest(model, this.Request);
            }

            return View(model);
        }
    }
}

NELCCG.NHSUKFrontend.MvcApp/Controllers/HomeController.cs
namespace NELCCG.NHSUKFrontend.MvcApp.Controllers
{
    using System.Collections.Generic;
    using System.Diagnostics;
    using Microsoft.AspNetCore.Diagnostics;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using NELCCG.NHSUKFrontend.MvcApp.Models;
    using NELCCG.NHSUKFrontend.Razor.Helpers;

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            this._logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SvgIcons()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var feature = this.HttpContext.Features.Get<IExceptionHandlerFeature>();
            this._logger.LogError(feature?.Error, feature?.Error.Message);
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier, Error = feature?.Error });
        }
    }
}

NELCCG.NHSUKFrontend.MvcApp/Controllers/NavigationController.cs
namespace NELCCG.NHSUKFrontend.MvcApp.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class NavigationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AtoZ()
        {
            return View();
        }

        public IActionResult Card()
        {
            return View();
        }

        public IActionResult ContentsList()
        {
            return View();
        }

        public IActionResult ListPanel()
        {
            return View();
        }

        public IActionResult Pagination()
        {
            return View();
        }
    }
}

NELCCG.NHSUKFrontend.MvcApp/Views/Content/CareCard.cshtml
@{
    ViewData["Title"] = ViewData["HeroTitle"] = "Care Card";
}

@section Head {
    <style>
        .open-q { background: #eee;}
        .open-q .nhsuk-care-card__content::before {
            color: red;
            font-size: 2.5em;
            content: "┌ ";
            position: absolute;
            margin-top: -1em;
            margin-left: -0.8em;
        }

        .close-q {
            position: relative;
        }

            .close-q .nhsuk-care-card__content::after {
                color: darkorange;
                font-size: 2.5em;
                content: " ┘";
                position: absolute;
                right: 0.1em;
                bottom: -0.1em;
            }
    </style>
}

@section PreContent {
    <nhsuk-breadcrumb>
        <nhsuk-breadcrumb-list>
            <a nhsuk-breadcrumb-item asp-controller="Home" asp-action="Index">Home</a>
            <a nhsuk-breadcrumb-item asp-action="Index">Content</a>
        </nhsuk-breadcrumb-list>
        <a nhsuk-breadcrumb-backlink asp-action="Index">Back to Content</a>
    </nhsuk-breadcrumb>
}

<div class="nhsuk-grid-row">
    <div class="nhsuk-grid-column-one-quarter">
        <nhsuk-contents-list>
            <nhsuk-contents-list-item text="Care Card" current></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Details / Expander" href="@Url.Action("Details")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Do and Don't Lists" href="@Url.Action("DoDontLists")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Hero" href="@Url.Action("Hero")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Image" href="@Url.Action("Image")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Inset text" href="@Url.Action("InsetText")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Summary list" href="@Url.Action("SummaryList")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Table" href="@Url.Action("Table")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Tag" href="@Url.Action("Tag")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Warning callout" href="@Url.Action("WarningCallout")"></nhsuk-contents-list-item>
        </nhsuk-contents-list>
    </div>
    <div class="nhsuk-grid-column-three-quarters">
        <nhsuk-care-card heading="Speak to a GP if:" type="NonUrgent">
            <ul>
                <li>Symptom one</li>
                <li>Symptom two</li>
                <li>Symptom three</li>
                <li>Symptom four</li>
            </ul>
        </nhsuk-care-card>

        <nhsuk-care-card heading="Ask for an urgent GP appointment if:" type="Urgent" classes="@(new[] { "open-q", "close-q" })">
            <ul>
                <li>Symptom one</li>
                <li>Symptom two</li>
                <li>Symptom three</li>
                <li>Symptom four</li>
            </ul>
        </nhsuk-care-card>

        <nhsuk-care-card heading="Call 999 if:" type="Immediate">
            <ul>
                <li>Symptom one</li>
                <li>Symptom two</li>
                <li>Symptom three</li>
                <li>Symptom four</li>
            </ul>
        </nhsuk-care-card>
    </div>
</div>

NELCCG.NHSUKFrontend.MvcApp/Views/Content/Details.cshtml
@{
    ViewData["Title"] = ViewData["HeroTitle"] = "Details / Expander";
}

@section PreContent {
    <nhsuk-breadcrumb>
        <nhsuk-breadcrumb-list>
            <a nhsuk-breadcrumb-item asp-controller="Home" asp-action="Index">Home</a>
            <a nhsuk-breadcrumb-item asp-action="Index">Content</a>
        </nhsuk-breadcrumb-list>
        <a nhsuk-breadcrumb-backlink asp-action="Index">Back to Content</a>
    </nhsuk-breadcrumb>
}

<div class="nhsuk-grid-row">
    <div class="nhsuk-grid-column-one-quarter">
        <nhsuk-contents-list>
            <nhsuk-contents-list-item text="Care Card" href="@Url.Action("CareCard")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Details / Expander" current></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Do and Don't Lists" href="@Url.Action("DoDontLists")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Hero" href="@Url.Action("Hero")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Image" href="@Url.Action("Image")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Inset Text" href="@Url.Action("InsetText")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Summary list" href="@Url.Action("SummaryList")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Table" href="@Url.Action("Table")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Tag" href="@Url.Action("Tag")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Warning callout" href="@Url.Action("WarningCallout")"></nhsuk-contents-list-item>
        </nhsuk-contents-list>
    </div>
    <div class="nhsuk-grid-column-three-quarters">
        <nhsuk-details summary="Details hidden">
            <p>Details go here</p>
        </nhsuk-details>

        <nhsuk-details summary="Details shown" open>
            <p>Details go here</p>
        </nhsuk-details>

        <nhsuk-details summary="Styled as expander" expander>
            <p>Details go here</p>
        </nhsuk-details>
    </div>
</div>

NELCCG.NHSUKFrontend.MvcApp/Views/Content/DoDontLists.cshtml
@{
    ViewData["Title"] = ViewData["HeroTitle"] = "Do and Don't Lists";
}

@section PreContent {
    <nhsuk-breadcrumb>
        <nhsuk-breadcrumb-list>
            <a nhsuk-breadcrumb-item asp-controller="Home" asp-action="Index">Home</a>
            <a nhsuk-breadcrumb-item asp-action="Index">Content</a>
        </nhsuk-breadcrumb-list>
        <a nhsuk-breadcrumb-backlink asp-action="Index">Back to Content</a>
    </nhsuk-breadcrumb>
}

<div class="nhsuk-grid-row">
    <div class="nhsuk-grid-column-one-quarter">
        <nhsuk-contents-list>
            <nhsuk-contents-list-item text="Care Card" href="@Url.Action("CareCard")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Details / Expander" href="@Url.Action("Details")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Do and Don't Lists" current></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Hero" href="@Url.Action("Hero")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Image" href="@Url.Action("Image")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Inset text" href="@Url.Action("InsetText")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Summary list" href="@Url.Action("SummaryList")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Table" href="@Url.Action("Table")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Tag" href="@Url.Action("Tag")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Warning callout" href="@Url.Action("WarningCallout")"></nhsuk-contents-list-item>
        </nhsuk-contents-list>
    </div>
    <div class="nhsuk-grid-column-three-quarters">
        <nhsuk-do-dont-list type="Do">
            <nhsuk-do-dont-list-item>cover blisters that are likely to burst with a soft plaster or dressing</nhsuk-do-dont-list-item>
            <nhsuk-do-dont-list-item>wash your hands before touching a burst blister</nhsuk-do-dont-list-item>
            <nhsuk-do-dont-list-item>allow the fluid in a burst blister to drain before covering it with a plaster or dressing</nhsuk-do-dont-list-item>
        </nhsuk-do-dont-list>

        <nhsuk-do-dont-list type="Dont">
            <nhsuk-do-dont-list-item>burst a blister yourself</nhsuk-do-dont-list-item>
            <nhsuk-do-dont-list-item>peel the skin off a burst blister</nhsuk-do-dont-list-item>
            <nhsuk-do-dont-list-item hide-prefix>do not pick at the edges of the remaining skin</nhsuk-do-dont-list-item>
            <nhsuk-do-dont-list-item>wear the shoes or use the equipment that caused your blister until it heals</nhsuk-do-dont-list-item>
        </nhsuk-do-dont-list>
    </div>
</div>

NELCCG.NHSUKFrontend.MvcApp/Views/Content/Hero.cshtml
@using NELCCG.NHSUKFrontend.Razor.TagHelpers
@model HeroExample
@{
    ViewData["Title"] = "Hero";
    ViewData["HeroTitle"] = Model.HeroTitle;
    ViewData["HeroMessage"] = Model.HeroMessage;
    ViewData["HeroImage"] = Model.HeroImage;
}
@section PreContent {
    <nhsuk-breadcrumb>
        <nhsuk-breadcrumb-list>
            <a nhsuk-breadcrumb-item asp-controller="Home" asp-action="Index">Home</a>
            <a nhsuk-breadcrumb-item asp-action="Index">Content</a>
        </nhsuk-breadcrumb-list>
        <a nhsuk-breadcrumb-backlink asp-action="Index">Back to Content</a>
    </nhsuk-breadcrumb>
}

<div class="nhsuk-grid-row">
    <div class="nhsuk-grid-column-one-quarter">
        <nhsuk-contents-list>
            <nhsuk-contents-list-item text="Care Card" href="@Url.Action("CareCard")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Details / Expander" href="@Url.Action("Details")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Do and Don't Lists" href="@Url.Action("DoDontLists")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Hero" current></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Image" href="@Url.Action("Image")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Inset text" href="@Url.Action("InsetText")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Summary list" href="@Url.Action("SummaryList")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Table" href="@Url.Action("Table")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Tag" href="@Url.Action("Tag")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Warning callout" href="@Url.Action("WarningCallout")"></nhsuk-contents-list-item>
        </nhsuk-contents-list>
    </div>
    <div class="nhsuk-grid-column-three-quarters">
        <form asp-action="Hero">
            <div class="nhsuk-inset-text nhsuk-u-margin-top-0">
                <span class="nhsuk-u-visually-hidden">Information: </span>
                <p>
                    Updating the details in this form will add a hero to the top of the page.
                    <strong>Known issue:</strong> adding an image and heading will partially hide the breadcrumb, on GitHub as
                    <a href="https://github.com/nhsuk/nhsuk-frontend/issues/431" rel="external">Hero image with image, heading and content margin (#431)</a>
                </p>
            </div>
            <nhsuk-fieldset>
                <nhsuk-fieldset-legend size="FieldsetLegendTagHelper.LegendSize.Medium" is-page-heading heading-level="2">Hero component properties</nhsuk-fieldset-legend>
                <nhsuk-form-group>
                    <nhsuk-input asp-for="HeroTitle">
                        <nhsuk-label asp-for="HeroTitle"></nhsuk-label>
                    </nhsuk-input>
                </nhsuk-form-group>
                <nhsuk-form-group>
                    <nhsuk-input asp-for="HeroMessage">
                        <nhsuk-label asp-for="HeroMessage"></nhsuk-label>
                    </nhsuk-input>
                </nhsuk-form-group>
                <nhsuk-form-group>
                    <nhsuk-input asp-for="HeroImage">
                        <nhsuk-label asp-for="HeroImage"></nhsuk-label>
                        <nhsuk-hint>Example: https://placekitten.com/g/1200/320 </nhsuk-hint>
                    </nhsuk-input>
                </nhsuk-form-group>
            </nhsuk-fieldset>

            <nhsuk-button type="Submit">
                Change Hero
            </nhsuk-button>
        </form>
    </div>
</div>

NELCCG.NHSUKFrontend.MvcApp/Views/Content/Image.cshtml
@{
    ViewData["Title"] = ViewData["HeroTitle"] = "Image";
}

@section PreContent {
    <nhsuk-breadcrumb>
        <nhsuk-breadcrumb-list>
            <a nhsuk-breadcrumb-item asp-controller="Home" asp-action="Index">Home</a>
            <a nhsuk-breadcrumb-item asp-action="Index">Content</a>
        </nhsuk-breadcrumb-list>
        <a nhsuk-breadcrumb-backlink asp-action="Index">Back to Content</a>
    </nhsuk-breadcrumb>
}
<div class="nhsuk-grid-row">
    <div class="nhsuk-grid-column-one-quarter">
        <nhsuk-contents-list>
            <nhsuk-contents-list-item text="Care Card" href="@Url.Action("CareCard")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Details / Expander" href="@Url.Action("Details")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Do and Don't Lists" href="@Url.Action("DoDontLists")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Hero" href="@Url.Action("Hero")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Image" current></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Inset text" href="@Url.Action("InsetText")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Summary list" href="@Url.Action("SummaryList")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Table" href="@Url.Action("Table")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Tag" href="@Url.Action("Tag")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Warning callout" href="@Url.Action("WarningCallout")"></nhsuk-contents-list-item>
        </nhsuk-contents-list>
    </div>
    <div class="nhsuk-grid-column-three-quarters">
        <nhsuk-image classes="@(new[] { "nhsuk-u-margin-top-0" })" src="https://placekitten.com/600/300" caption="Image caption" />

        <nhsuk-image src="https://placehold.co/320x150/333333/fff?text=small"
                     sizes="(min-width: 1020px) 320px, (min-width: 768px) 50vw, 100vw"
                     srcset="https://placehold.co/640x300/333333/fff?text=medium 640w, https://placehold.co/800x375/333333/fff?text=large 800w"
                     caption="<code>srcset</code> test. Resize or use responsive mode to see the different images" />
    </div>
</div>

NELCCG.NHSUKFrontend.MvcApp/Views/Content/Index.cshtml
@{
    ViewData["Title"] = ViewData["HeroTitle"] = "Content";
}
@section PreContent {
    <nhsuk-breadcrumb>
        <nhsuk-breadcrumb-list>
            <a nhsuk-breadcrumb-item asp-controller="Home">Home</a>
        </nhsuk-breadcrumb-list>
        <a nhsuk-breadcrumb-backlink asp-controller="Home">Go Home</a>
    </nhsuk-breadcrumb>
}
<div class="nhsuk-grid-row">
    <div class="nhsuk-grid-column-one-quarter">
        <nhsuk-contents-list>
            <nhsuk-contents-list-item text="Care Card" href="@Url.Action("CareCard")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Details / Expander" href="@Url.Action("Details")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Do and Don't List" href="@Url.Action("DoDontLists")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Hero" href="@Url.Action("Hero")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Image" href="@Url.Action("Image")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Inset text" href="@Url.Action("InsetText")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Summary list" href="@Url.Action("SummaryList")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Table" href="@Url.Action("Table")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Tag" href="@Url.Action("Tag")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Warning callout" href="@Url.Action("WarningCallout")"></nhsuk-contents-list-item>
        </nhsuk-contents-list>
    </div>
    <div class="nhsuk-grid-column-three-quarters">
        Please select a page in the navigation menu.
    </div>
</div>

NELCCG.NHSUKFrontend.MvcApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome";
    ViewData["HeroTitle"] = "Sample site";
    ViewData["HeroMessage"] = "Example site using Razor components.";
}
<div>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <nhsuk-list ordered-list>
        <li>
            <a nhsuk-action-link asp-controller="Content">Content</a>
        </li>
        <li>
            <a nhsuk-action-link asp-controller="Form">Form Elements</a>
        </li>
        <li>
            <a nhsuk-action-link asp-controller="Navigation">Navigation</a>
        </li>
        <li>
            <a nhsuk-action-link asp-action="SvgIcons">SVG Icons</a>
        </li>
    </nhsuk-list>
</div>

NELCCG.NHSUKFrontend.MvcApp/Views/Navigation/ContentsList.cshtml
@{
    ViewData["Title"] = ViewData["HeroTitle"] = "Contents List";
}

@section PreContent {
    <nhsuk-breadcrumb>
        <nhsuk-breadcrumb-list>
            <a nhsuk-breadcrumb-item asp-controller="Home" asp-action="Index">Home</a>
            <a nhsuk-breadcrumb-item asp-action="Index">Navigation</a>
        </nhsuk-breadcrumb-list>
        <a nhsuk-breadcrumb-backlink asp-action="Index">Back to Navigation</a>
    </nhsuk-breadcrumb>
}

<div class="nhsuk-grid-row">
    <div class="nhsuk-grid-column-one-quarter">
        <nhsuk-contents-list>
            <nhsuk-contents-list-item text="A - Z" href="@Url.Action("AtoZ")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Card" href="@Url.Action("Card")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Contents List" current></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="List Panel" href="@Url.Action("ListPanel")"></nhsuk-contents-list-item>
            <nhsuk-contents-list-item text="Pagination" href="@Url.Action("Pagination")"></nhsuk-contents-list-item>
        </nhsuk-contents-list>
    </div>
    <div class="nhsuk-grid-column-three-quarters">
        Currently used in this and related pages.
    </div>
</div>

NELCCG.NHSUKFrontend.MvcApp/Views/Shared/_Layout.cshtml
@using NELCCG.NHSUKFrontend.Razor.Models
@{
    var headerProperties = new HeaderProperties
    {
        Organisation = new Organisation { Name = "NHS North East Lincolnshire", Descriptor = "Clinical Commissioning Group" },
        PrimaryLinks = new Link[]
        {
            new Link { Label = "Content", Url = Url.Action("Index", "Content") },
            new Link { Label = "Form Elements", Url = Url.Action("Index", "Form") },
            new Link { Label = "Navigation", Url = Url.Action("Index", "Navigation") },
            new Link { Label = "SVG Icons", Url = Url.Action("SvgIcons", "Home") },
        },
        ShowNav = true
    };

    var footerProperties = new FooterProperties
    {
        Copyright = "© 2021 NHS North East Lincolnshire",
        Links = new Link[]
        {
            new Link { Label = "Privacy", Url = Url.Action("Privacy", "Home") }
        }
    };
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcApp</title>
    <link nhsuk-frontend-version="Version__5_2_1" />
    <link rel="stylesheet" href="~/css/site.css" />
    @await RenderSectionAsync("Head", required: false)
</head>
<body>
    <nhsuk-skip-link>Skip to main content</nhsuk-skip-link>
    <vc:header properties="@headerProperties"></vc:header>
    <nhsuk-hero heading="@ViewData["HeroTitle"]" text="@ViewData["HeroMessage"]" image-url="@ViewData["HeroImage"]"></nhsuk-hero>
    @await RenderSectionAsync("PreContent", required: false)
    <div class="nhsuk-width-container">
        <main role="main" id="maincontent" class="nhsuk-main-wrapper">
            @RenderBody()
        </main>
    </div>
    <vc:footer properties="@footerProperties"></vc:footer>
    <script nhsuk-frontend-version="Version__5_2_1"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>